### ISSUE TITLE
Fix cache parser for lower case input string

### ISSUE THREAD

**Issue by giucris** [giucris/yasp#48]
**Describe the bug**
The Yasp parser raises an exception when attempting to parse a cache field in lower or upper case.

**To Reproduce**
1. Create a yml file with the following source config: 
```yml
.
.
.
sources:
    - id: users
      source:
        format: csv
        options:
          path: examples/example-1/input/
          header: 'true'
      cache: MEMORY
.
.
.
...
```
3. run java -jar yasp-app-0.0.1-SNAPSHOT.jar --file `${path to the file}`
4. And the following exception will be raised: 
```exception
Exception in thread "main" scala.MatchError: MEMORY (of class java.lang.String)
        at it.yasp.app.support.DecodersSupport.$anonfun$cacheLayerDecoder$2(DecodersSupport.scala:46)
```
**Expected behavior**
Parse without failure

**Environment (please describe your environment):**
- Windows 11
- JDK 8
