### ISSUE TITLE
Added support for custom source process and destination

### ISSUE THREAD

**Issue by giucris** [giucris/yasp#56]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to execute custom code for any type of operation.
This may be a limitation in use.

**Describe the solution you'd like**
Probably the best solution is to expose libraries to build yasp plugins for reader writers and processors. Something like 
```yaml
....
source:
  classPath: my.plugin.classpath
  options: 
      x: y
...
```
And then the users should provide the jar with the proper plugin implementation

**Describe alternatives you've considered**
...

**Additional context**
...
