### ISSUE TITLE
Simplify YaspPlan with flat structure

### ISSUE THREAD

**Issue by giucris** [giucris/yasp#88]
**Describe the solution you'd like**
Currently YaspPlan it take source, process and sink. It could be useful and more readable if yasp plan is a flat list that take in input any YaspAction. 

For example:
**Current**:
```yml
...
...
plan:   
  sources:
    - id: my_csv      
      source:           
        format: csv   
        options:       
          header: 'true'
          path: path/to/input/csv/
  processes:
    - id: my_csv_filtered   
      process:              
        query: >-         
          SELECT * 
          FROM my_csv 
          WHERE id=1
  sinks:                   
    - id: my_csv_filtered  
      dest:                 
        format: csv     
        options:          
          header: 'true'
          path: path/to/out/csv/
```

This could be simplified using a flat list as follow:
```yml
...
...
plan:   
    - id: my_csv      
      source:           
        format: csv   
        options:       
          header: 'true'
          path: path/to/input/csv/
    - id: my_csv_filtered   
      process:              
        query: >-         
          SELECT * 
          FROM my_csv 
          WHERE id=1
    - id: my_csv_filtered  
      dest:                 
        format: csv     
        options:          
          header: 'true'
          path: path/to/out/csv/
```

**Describe alternatives you've considered**
No alternatives considered

**Additional context**
