### ISSUE TITLE
Add some model to reduce complexity for most used source and sink

### ISSUE THREAD

**Issue by giucris** [giucris/yasp#89]
**Describe the solution you'd like**
In some cases it could be annoying to write the full format configuration for the most common source and sink. 
It could be useful to have some facility 

For example:
```yml
...
    - id: my_csv      
      source:           
        format: csv   
        options:       
          header: 'true'
          path: path/to/input/csv/
```

It could be done in the following way:
```yml
...
    - id: my_csv      
      source:           
        csv: path/to/input/csv/
        options:       
          header: 'true' 
```
